(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["components/uni-pagination/uni-pagination"],{"2b01":function(t,n,e){"use strict";e.r(n);var r=e("e397"),i=e.n(r);for(var u in r)"default"!==u&&function(t){e.d(n,t,function(){return r[t]})}(u);n["default"]=i.a},"66a5":function(t,n,e){"use strict";var r=e("75f2"),i=e.n(r);i.a},"712d":function(t,n,e){"use strict";var r=function(){var t=this,n=t.$createElement;t._self._c},i=[];e.d(n,"a",function(){return r}),e.d(n,"b",function(){return i})},"75f2":function(t,n,e){},c64a:function(t,n,e){"use strict";e.r(n);var r=e("712d"),i=e("2b01");for(var u in i)"default"!==u&&function(t){e.d(n,t,function(){return i[t]})}(u);e("66a5");var c=e("2877"),a=Object(c["a"])(i["default"],r["a"],r["b"],!1,null,"6e7e7126",null);n["default"]=a.exports},e397:function(t,n,e){"use strict";Object.defineProperty(n,"__esModule",{value:!0}),n.default=void 0;var r=function(){return Promise.all([e.e("common/vendor"),e.e("components/uni-icons/uni-icons")]).then(e.bind(null,"e677"))},i={name:"UniPagination",components:{uniIcons:r},props:{prevText:{type:String,default:"上一页"},nextText:{type:String,default:"下一页"},current:{type:[Number,String],default:1},total:{type:[Number,String],default:0},pageSize:{type:[Number,String],default:10},showIcon:{type:[Boolean,String],default:!1},canClick:{type:Boolean,default:!0}},data:function(){return{currentIndex:1}},computed:{maxPage:function(){var t=1,n=Number(this.total),e=Number(this.pageSize);return n&&e&&(t=Math.ceil(n/e)),t}},watch:{current:function(t){this.currentIndex=+t}},created:function(){this.currentIndex=+this.current},methods:{clickLeft:function(){1!==Number(this.currentIndex)&&this.canClick&&(this.currentIndex-=1,this.change("prev"))},clickRight:function(){Number(this.currentIndex)!==this.maxPage&&this.canClick&&(this.currentIndex+=1,this.change("next"))},change:function(t){this.$emit("change",{type:t,current:this.currentIndex})}}};n.default=i}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'components/uni-pagination/uni-pagination-create-component',
    {
        'components/uni-pagination/uni-pagination-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('543d')['createComponent'](__webpack_require__("c64a"))
        })
    },
    [['components/uni-pagination/uni-pagination-create-component']]
]);                
