(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["components/message"],{"0725":function(t,n,e){"use strict";Object.defineProperty(n,"__esModule",{value:!0}),n.default=void 0;var o={name:"bobo-message-cpt",props:{zIndex:{type:Number,default:1e4},duration:{type:Number,default:2e3},background:{type:Boolean,default:!1}},data:function(){return{messageQueue:[],lastId:0}},computed:{backgroundClass:function(){var t=this;return function(n){return t.background||n.background?"background-".concat(n.type):""}}},methods:{info:function(t){var n={type:"info"};"object"===typeof t&&t?(n.content=t.content,n.duration=t.duration,n.background=t.background):"string"===typeof t&&(n.content=t),this.fadeIn(n)},success:function(t){var n={type:"success"};"object"===typeof t&&t?(n.content=t.content,t.duration&&"number"===typeof t.duration&&t.duration>=0&&(n.duration=t.duration),n.background=t.background):"string"===typeof t&&(n.content=t),this.fadeIn(n)},warn:function(t){var n={type:"warn"};"object"===typeof t&&t?(n.content=t.content,t.duration&&"number"===typeof t.duration&&t.duration>=0&&(n.duration=t.duration),n.background=t.background):"string"===typeof t&&(n.content=t),this.fadeIn(n)},error:function(t){var n={type:"error"};"object"===typeof t&&t?(n.content=t.content,t.duration&&"number"===typeof t.duration&&t.duration>=0&&(n.duration=t.duration),n.background=t.background):"string"===typeof t&&(n.content=t),this.fadeIn(n)},fadeIn:function(t){var n=this;t.id=this.generateId(),t.animation="fadeIn",this.messageQueue.push(t),setTimeout(function(){t.animation=""},410),setTimeout(function(){n.fadeOut(t)},t.duration||this.duration)},fadeOut:function(t){var n=this;t.animation="fadeOut",setTimeout(function(){var e=0;n.messageQueue.some(function(n,o){if(n.id===t.id)return e=o,!0}),n.messageQueue.splice(e,1)},500)},generateId:function(){return 1e3*(new Date).getTime()+this.lastId++%1e3}}};n.default=o},"229d":function(t,n,e){"use strict";var o=e("4c8e"),u=e.n(o);u.a},"4c8e":function(t,n,e){},"5b69":function(t,n,e){"use strict";e.r(n);var o=e("b083"),u=e("827a");for(var a in u)"default"!==a&&function(t){e.d(n,t,function(){return u[t]})}(a);e("229d");var r=e("2877"),i=Object(r["a"])(u["default"],o["a"],o["b"],!1,null,"bb416a40",null);n["default"]=i.exports},"827a":function(t,n,e){"use strict";e.r(n);var o=e("0725"),u=e.n(o);for(var a in o)"default"!==a&&function(t){e.d(n,t,function(){return o[t]})}(a);n["default"]=u.a},b083:function(t,n,e){"use strict";var o=function(){var t=this,n=t.$createElement,e=(t._self._c,t.__map(t.messageQueue,function(n,e){var o=t.backgroundClass(n);return{$orig:t.__get_orig(n),m0:o}}));t.$mp.data=Object.assign({},{$root:{l0:e}})},u=[];e.d(n,"a",function(){return o}),e.d(n,"b",function(){return u})}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'components/message-create-component',
    {
        'components/message-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('543d')['createComponent'](__webpack_require__("5b69"))
        })
    },
    [['components/message-create-component']]
]);                
